azs:
- name: z1
  cloud_properties:
    availability_zone: us-east-1a
- name: z2
  cloud_properties:
    availability_zone: us-east-1b
- name: z3
  cloud_properties:
    availability_zone: us-east-1c
vm_types:
- name: default
  cloud_properties:
    instance_type: m4.large
    ephemeral_disk: {size: 25_000}
- name: large
  cloud_properties:
    instance_type: m4.xlarge
    ephemeral_disk: {size: 50_000}
disk_types:
- name: default
  disk_size: 25_000
- name: large
  disk_size: 50_000
networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.16.0/20
    gateway: 10.0.16.1
    azs: [z1, z2, z3]
    dns: [8.8.8.8]
    reserved: [10.0.16.1-10.0.16.10]
    cloud_properties:
      subnet: subnet-0b00c019fe34b506a
- name: vip
  type: vip
compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
